### ISSUE TITLE
Laravel 5.5

### ISSUE THREAD

**Issue by ngugijames** [faustbrian/Laravel-Cookie-Consent#11]
hello,

Is there any plan to support L5.5
I also noticed the the service provider package that this repo depends on is now abandoned, are you planning to continue supporting this?

**Comment by faustbrian** [comment]
Will be fixed in a few hours.

⁣Sent from TypeApp ​

**Comment by faustbrian** [comment]
https://github.com/faustbrian/Laravel-Cookie-Consent/releases/tag/4.0.0
